dotenv: .env
wallets:
    from_key: ${PRIVATE_KEY}
dependencies:
    - smartcontractkit/chainlink-brownie-contracts@1.2.0
compiler:
    solc:
        remappings:
            - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0'
networks:
    default: dev
    dev:
        verify: false
    ganache-local:
        verify: false
    rinkeby:
        eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
        verify: true
